### PR TITLE
Fixes for upload canceling #61

### PR DESCRIPTION
**Pull request by Codes4Fun**

### CODE REVIEW

**Comment by exsilium** [comment]
Firstly, thank you for the patch, @Codes4Fun ! I haven't really used much of the upload feature to know what are the current limitations but I did try to test your patch and doing so found the following:

1. The cancel works as in that the transfer gets closed but the temporary file is left behind in the folder
2. Once cancelled, I don't seem to be able to start any new uploads to the same nor different directory - I must reload the UI to do so

Wanted to know if you are experiencing any of the same behaviors? Having said that, I believe this patch improves the current state of the file upload functionality (where the cancel didn't work at all) so from that point of view I'm totally ok to pull this if you don't want to work on it any further.

Cheers!

**Comment by Codes4Fun** [comment]
I don't think this is ready. It seems to be a weird thing happening with this code and Firefox, onreadystatechange is not being called on abort. In Firefox with smaller tests onreadystatechange is being called on abort but not with this code for some reason. It could be a timing thing, but I would think it would be more random instead of consistently failing.

If I can't figure this out, I may try to do it without the abort, and let the last XMLHttpRequest complete on its own and handling the cancel. I just worry about slow transfers and the UI reflecting that canceling is in progress, I think it might be there already though.

**Comment by Codes4Fun** [comment]
I've looked at the Firefox code, and I think it is a bug in Firefox to do with web Workers and Uploads.

I've created a test case outside of Pylon that also fails in Firefox that I can use to further investigate that bug, or possibly submit it as an issue for mozilla to look at. So that will be separate from this.

I am not sure yet how I will fix this in Pylon, the UI does not reflect that a file has not been completely canceled yet. So at slow upload speeds, there could be a period where it is still uploading even though it looks canceled and a user could try to upload and weird things happen.

**Comment by Codes4Fun** [comment]
The incomplete file is expected. I could change that to automatically deleting the file as well.

Another big problem is, if the user refreshes the web browser during an upload, the server is left in a state of expecting more file chunks. If the user then tries to upload again, the server will append to the existing temporary file, and there is a high chance that it gets permanently stuck in an incomplete state, where the temporary file is never renamed to the actual file name and is never visible to the user, and all uploads of the same file just keep growing the temporary file. The only solution right now for an end user is to restart the server and delete the temporary file.

We basically lack any kind of information between the server and the client regarding states. There is no way for the client to signal to the server to start uploading a fresh file (replacing temporary files), or to clear out temporary files. My solution was for the client to lie that a file is complete, making the temporary file visible to the end user, who can then delete it or replace it with another upload.

If I were to figure out a good solution to that problem, canceling may be better incorporated into that.

I'm going to look at options for solving this. I was reluctant to change the server side code but that may be the best way to do it. Maybe I could somehow provide information that a chunk is the first file chunk, and server getting that would reset the temporary file. This would mean I can abort and not need to depend on onreadystatechange, and the Firefox issue would be resolved, a second upload would reset the temporary file.

**Comment by Codes4Fun** [comment]
So in testing a potential fix, I found an infinite callback loop in vfs-local code.

I added code on the server to end a previous stream, but the end will almost always rename the temporary file to the final file name, to prevent that you can emit an error that will set a flag and the temporary file will not be renamed. When I did this I noticed the error message was repeatedly spammed to the terminal.

What I found is that upon emitting the error, the error handler does an fs.unlink on the temporary file:

https://github.com/pylonide/vfs-local/blob/890b96c73747a677d3a46ce7f97ae3c78d9f0f5c/localfs.js#L570-L573

https://github.com/pylonide/vfs-local/blob/890b96c73747a677d3a46ce7f97ae3c78d9f0f5c/localfs.js#L459-L462

the callback they reuse everywhere then emits an error again, which restarts the loop. (note ```writable``` and ```meta.stream``` are the same)

https://github.com/pylonide/vfs-local/blob/890b96c73747a677d3a46ce7f97ae3c78d9f0f5c/localfs.js#L427-L430

**Comment by exsilium** [comment]
A good find concerning the error emitter loop. If you do have a proposal for `vfs-local` fix, make sure to file that separately. Without making things more difficult.. for now, I do suggest to merge this fix as is and leave the incomplete file for the user to delete. 🎉

**Comment by Codes4Fun** [comment]
I committed my changes.

**Comment by exsilium** [comment]
Thank you @Codes4Fun for your time on this! Cheers! :beers:

**Pull request merged**
